<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="dvtcstests048" failures="0" tests="1" name="testscripts.scenario1.NaturalPhenomenonS1_LT" time="133.418" errors="1" timestamp="2024-03-27T12:14:10 IST" skipped="0">
  <testcase classname="testscripts.scenario1.NaturalPhenomenonS1_LT" name="runTC1" time="133.418">
    <error message="Cannot invoke &quot;com.LT.framework.selenium.SeleniumReport.updateTestLog(String, String, com.LT.framework.Status)&quot; because &quot;this.report&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.LT.framework.selenium.SeleniumReport.updateTestLog(String, String, com.LT.framework.Status)" because "this.report" is null
at supportlibraries.ZephyrUtils.updateJIRAExecutionStatus(ZephyrUtils.java:402)
at supportlibraries.DriverScript.setJiraStatus(DriverScript.java:703)
at supportlibraries.DriverScript.wrapUp(DriverScript.java:656)
at supportlibraries.DriverScript.driveTestExecution(DriverScript.java:121)
at testscripts.scenario1.NaturalPhenomenonS1_LT.runTC1(NaturalPhenomenonS1_LT.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
    </error>
  </testcase> <!-- runTC1 -->
</testsuite> <!-- testscripts.scenario1.NaturalPhenomenonS1_LT -->
